// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyjWh1QK1MkGykNT4POqqRLabHwhxHG2I',
    appId: '1:1042673137979:android:5b23784304eee9254c9f1e',
    messagingSenderId: '1042673137979',
    projectId: 'haya-by-faith',
    storageBucket: 'haya-by-faith.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKNqlBQYTAaY-rvudaV1nxuetI9Tod2Sg',
    appId: '1:1042673137979:ios:d3680ea1be92d6804c9f1e',
    messagingSenderId: '1042673137979',
    projectId: 'haya-by-faith',
    storageBucket: 'haya-by-faith.firebasestorage.app',
    iosBundleId: 'org.elhaya.hayati',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_IfuzlSWPnyD4kD2xSnevlpDBvnTIsC4',
    appId: '1:1042673137979:web:18f72622e339ac1f4c9f1e',
    messagingSenderId: '1042673137979',
    projectId: 'haya-by-faith',
    authDomain: 'haya-by-faith.firebaseapp.com',
    storageBucket: 'haya-by-faith.firebasestorage.app',
    measurementId: 'G-5R907G8KD9',
  );

}